base:
  use_cuda: True

data:
  dataset_folder: data
  images_folder: images_total_data
  train_dataset: train.json
  val_dataset: dev.json
  test_dataset: test.json

tokenizer:
  padding: longest
  max_length: 64
  truncation: True
  return_token_type_ids: True
  return_attention_mask: True

text_embedding:
  text_encoder: bert-base-multilingual-uncased
  d_features: 768
  d_model: 512
  dropout: 0.1

vision_embedding:
  image_encoder: google/vit-base-patch16-224-in21k
  d_features: 768
  d_model: 512
  dropout: 0.1

attention:
  layers: 3
  heads: 8
  d_model: 512
  d_key: 64
  d_value: 64
  d_ff: 2048
  d_feature: 2048
  dropout: 0.1
  use_aoa: False

encoder:
  d_model: 512
  layers: 3

decoder:
  text_decoder: bert-base-multilingual-uncased
  d_model: 512
  layers: 3
  max_len: 64

model:
  name: mbert-vit  # Custom name for the multimodal model
  intermediate_dims: 512
  dropout: 0.3

early_stoping:
  early_stopping_patience: 5

train:
  output_dir: checkpoint
  seed: 12345
  num_train_epochs: 100
  learning_rate: 5.0e-5
  weight_decay: 0.0
  warmup_ratio: 0.0
  warmup_steps: 0
  evaluation_strategy: epoch
  logging_strategy: epoch
  save_strategy: epoch
  save_total_limit: 2 
  metric_for_best_model: accuracy
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  remove_unused_columns: False
  dataloader_num_workers: 2
  load_best_model_at_end: True


metrics:
  metrics_folder: metrics
  metrics_file: metrics.json

inference:
  checkpoint: checkpoint-3