base:
  use_cuda: True

old_data:
  images_folder: images_total_data
  train_dataset: train.json
  val_dataset:  dev.json
  test_dataset: test.json
  resize: False
  image_H: 512
  image_W: 512

data:
  dataset_folder: data
  images_folder: images
  all_qa_pairs_file: all_qa_pairs.txt
  train_dataset: train.csv
  val_dataset: dev.csv
  test_dataset: test.csv
  question_col: question
  image_col: image_id
  answer_col: answers
  answer_space: answer_space.txt

tokenizer:
  padding: longest
  max_length: 64
  truncation: True
  return_token_type_ids: True
  return_attention_mask: True

model:
  name: mbert-vit  # Custom name for the multimodal model
  text_encoder: bert-base-multilingual-uncased # Valid transformer model for text encoding from HuggingFace
  image_encoder: google/vit-base-patch16-224-in21k  # Valid transformer model for image encoding from HuggingFace
  intermediate_dims: 512
  dropout: 0.3
  heads: 4

early_stoping:
  early_stopping_patience: 5

train:
  output_dir: checkpoint
  seed: 12345
  num_train_epochs: 100
  learning_rate: 5.0e-5
  weight_decay: 0.0
  warmup_ratio: 0.0
  warmup_steps: 0
  evaluation_strategy: epoch
  logging_strategy: epoch
  save_strategy: epoch
  save_total_limit: 2 
  metric_for_best_model: accuracy
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  remove_unused_columns: False
  dataloader_num_workers: 2
  load_best_model_at_end: True


metrics:
  metrics_folder: metrics
  metrics_file: metrics.json

inference:
  checkpoint: checkpoint-3